name: Min-imal
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82348
title: Min-imal
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-65158648-3
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.6412777432706207
purpose: []
